// <auto-generated />
using System;
using JackalWebHost2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JackalWebHost2.Migrations
{
    [DbContext(typeof(JackalDbContext))]
    [Migration("20250612172335_GamesTable_AddAdditionalData")]
    partial class GamesTable_AddAdditionalData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JackalWebHost2.Data.Entities.GameEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<bool>("GameOver")
                        .HasColumnType("boolean");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("MapSize")
                        .HasColumnType("integer");

                    b.Property<string>("TilesPackName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("JackalWebHost2.Data.Entities.GamePlayerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<byte>("MapPositionId")
                        .HasColumnType("smallint");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("JackalWebHost2.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JackalWebHost2.Data.Entities.GameEntity", b =>
                {
                    b.HasOne("JackalWebHost2.Data.Entities.UserEntity", "CreatorUser")
                        .WithMany("Games")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("JackalWebHost2.Data.Entities.GamePlayerEntity", b =>
                {
                    b.HasOne("JackalWebHost2.Data.Entities.GameEntity", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JackalWebHost2.Data.Entities.UserEntity", "User")
                        .WithMany("GamePlayers")
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JackalWebHost2.Data.Entities.GameEntity", b =>
                {
                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("JackalWebHost2.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("GamePlayers");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
