namespace Jackal.Core
{
    public enum TileType
    {
        Unknown,
        Water,
        Grass,
        Chest1,
        Chest2,
        Chest3,
        Chest4,
        Chest5,
        Fort,
        RespawnFort,
        RumBarrel,
        Horse,
        Arrow,
        Balloon,
        Ice,
        Airplane,
        Crocodile,
        Spinning,
        Trap,
        Cannibal,
		Cannon,
        Lighthouse,
        BenGunn,
        Caramba
    }
}